name: cofrinho_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  shared_preferences: ^2.3.3
  material_symbols_icons: ^4.2810.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_lints: ^3.0.0

flutter:
  assets:
  - assets/images/
  uses-material-design: true
